// Keyboard layouts definitions

export const layouts = {
  standard: {
    name: '标准104键',
    rows: [
      [
        { code: 'Escape', label: 'Esc', width: 1 }, null,
        { code: 'F1', label: 'F1', width: 1 },
        { code: 'F2', label: 'F2', width: 1 },
        { code: 'F3', label: 'F3', width: 1 },
        { code: 'F4', label: 'F4', width: 1 }, null,
        { code: 'F5', label: 'F5', width: 1 },
        { code: 'F6', label: 'F6', width: 1 },
        { code: 'F7', label: 'F7', width: 1 },
        { code: 'F8', label: 'F8', width: 1 }, null,
        { code: 'F9', label: 'F9', width: 1 },
        { code: 'F10', label: 'F10', width: 1 },
        { code: 'F11', label: 'F11', width: 1 },
        { code: 'F12', label: 'F12', width: 1 }, null,
        { code: 'PrintScreen', label: 'PrtSc', width: 1 },
        { code: 'ScrollLock', label: 'ScrLk', width: 1 },
        { code: 'Pause', label: 'Pause', width: 1 }
      ],
      [
        { code: 'Backquote', label: '`', width: 1 },
        { code: 'Digit1', label: '1', width: 1 },
        { code: 'Digit2', label: '2', width: 1 },
        { code: 'Digit3', label: '3', width: 1 },
        { code: 'Digit4', label: '4', width: 1 },
        { code: 'Digit5', label: '5', width: 1 },
        { code: 'Digit6', label: '6', width: 1 },
        { code: 'Digit7', label: '7', width: 1 },
        { code: 'Digit8', label: '8', width: 1 },
        { code: 'Digit9', label: '9', width: 1 },
        { code: 'Digit0', label: '0', width: 1 },
        { code: 'Minus', label: '-', width: 1 },
        { code: 'Equal', label: '=', width: 1 },
        { code: 'Backspace', label: 'Backspace', width: 2 }, null,
        { code: 'Insert', label: 'Insert', width: 1 },
        { code: 'Home', label: 'Home', width: 1 },
        { code: 'PageUp', label: 'Page Up', width: 1 }
      ],
      [
        { code: 'Tab', label: 'Tab', width: 1.5 },
        { code: 'KeyQ', label: 'Q', width: 1 },
        { code: 'KeyW', label: 'W', width: 1 },
        { code: 'KeyE', label: 'E', width: 1 },
        { code: 'KeyR', label: 'R', width: 1 },
        { code: 'KeyT', label: 'T', width: 1 },
        { code: 'KeyY', label: 'Y', width: 1 },
        { code: 'KeyU', label: 'U', width: 1 },
        { code: 'KeyI', label: 'I', width: 1 },
        { code: 'KeyO', label: 'O', width: 1 },
        { code: 'KeyP', label: 'P', width: 1 },
        { code: 'BracketLeft', label: '[', width: 1 },
        { code: 'BracketRight', label: ']', width: 1 },
        { code: 'Backslash', label: '\\', width: 1.5 }, null,
        { code: 'Delete', label: 'Delete', width: 1 },
        { code: 'End', label: 'End', width: 1 },
        { code: 'PageDown', label: 'Page Down', width: 1 }
      ],
      [
        { code: 'CapsLock', label: 'Caps Lock', width: 1.75 },
        { code: 'KeyA', label: 'A', width: 1 },
        { code: 'KeyS', label: 'S', width: 1 },
        { code: 'KeyD', label: 'D', width: 1 },
        { code: 'KeyF', label: 'F', width: 1 },
        { code: 'KeyG', label: 'G', width: 1 },
        { code: 'KeyH', label: 'H', width: 1 },
        { code: 'KeyJ', label: 'J', width: 1 },
        { code: 'KeyK', label: 'K', width: 1 },
        { code: 'KeyL', label: 'L', width: 1 },
        { code: 'Semicolon', label: ';', width: 1 },
        { code: 'Quote', label: "'", width: 1 },
        { code: 'Enter', label: 'Enter', width: 2.25 }
      ],
      [
        { code: 'ShiftLeft', label: 'Shift', width: 2.25 },
        { code: 'KeyZ', label: 'Z', width: 1 },
        { code: 'KeyX', label: 'X', width: 1 },
        { code: 'KeyC', label: 'C', width: 1 },
        { code: 'KeyV', label: 'V', width: 1 },
        { code: 'KeyB', label: 'B', width: 1 },
        { code: 'KeyN', label: 'N', width: 1 },
        { code: 'KeyM', label: 'M', width: 1 },
        { code: 'Comma', label: ',', width: 1 },
        { code: 'Period', label: '.', width: 1 },
        { code: 'Slash', label: '/', width: 1 },
        { code: 'ShiftRight', label: 'Shift', width: 2.75 }, null, null,
        { code: 'ArrowUp', label: '↑', width: 1 }, null, null,
        { code: 'NumLock', label: 'Num Lock', width: 1 },
        { code: 'NumpadDivide', label: '/', width: 1 },
        { code: 'NumpadMultiply', label: '*', width: 1 },
        { code: 'NumpadSubtract', label: '-', width: 1 }
      ],
      [
        { code: 'ControlLeft', label: 'Ctrl', width: 1.25 },
        { code: 'MetaLeft', label: 'Win', width: 1.25 },
        { code: 'AltLeft', label: 'Alt', width: 1.25 },
        { code: 'Space', label: 'Space', width: 6.25 },
        { code: 'AltRight', label: 'Alt', width: 1.25 },
        { code: 'MetaRight', label: 'Win', width: 1.25 },
        { code: 'ContextMenu', label: 'Menu', width: 1.25 },
        { code: 'ControlRight', label: 'Ctrl', width: 1.25 }, null, null,
        { code: 'ArrowLeft', label: '←', width: 1 },
        { code: 'ArrowDown', label: '↓', width: 1 },
        { code: 'ArrowRight', label: '→', width: 1 }, null, null,
        { code: 'Numpad7', label: '7', width: 1 },
        { code: 'Numpad8', label: '8', width: 1 },
        { code: 'Numpad9', label: '9', width: 1 },
        { code: 'NumpadAdd', label: '+', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad4', label: '4', width: 1 },
        { code: 'Numpad5', label: '5', width: 1 },
        { code: 'Numpad6', label: '6', width: 1 }, null,
        { code: 'Numpad1', label: '1', width: 1 },
        { code: 'Numpad2', label: '2', width: 1 },
        { code: 'Numpad3', label: '3', width: 1 },
        { code: 'NumpadEnter', label: 'Enter', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad0', label: '0', width: 2 },
        { code: 'NumpadDecimal', label: '.', width: 1 }
      ]
    ]
  },
  
  mac: {
    name: 'Mac键盘',
    rows: [
      [
        { code: 'Escape', label: 'Esc', width: 1 }, null,
        { code: 'F1', label: 'F1', width: 1 },
        { code: 'F2', label: 'F2', width: 1 },
        { code: 'F3', label: 'F3', width: 1 },
        { code: 'F4', label: 'F4', width: 1 }, null,
        { code: 'F5', label: 'F5', width: 1 },
        { code: 'F6', label: 'F6', width: 1 },
        { code: 'F7', label: 'F7', width: 1 },
        { code: 'F8', label: 'F8', width: 1 }, null,
        { code: 'F9', label: 'F9', width: 1 },
        { code: 'F10', label: 'F10', width: 1 },
        { code: 'F11', label: 'F11', width: 1 },
        { code: 'F12', label: 'F12', width: 1 }, null,
        { code: 'F13', label: 'F13', width: 1 },
        { code: 'F14', label: 'F14', width: 1 },
        { code: 'F15', label: 'F15', width: 1 }
      ],
      [
        { code: 'Backquote', label: '`', width: 1 },
        { code: 'Digit1', label: '1', width: 1 },
        { code: 'Digit2', label: '2', width: 1 },
        { code: 'Digit3', label: '3', width: 1 },
        { code: 'Digit4', label: '4', width: 1 },
        { code: 'Digit5', label: '5', width: 1 },
        { code: 'Digit6', label: '6', width: 1 },
        { code: 'Digit7', label: '7', width: 1 },
        { code: 'Digit8', label: '8', width: 1 },
        { code: 'Digit9', label: '9', width: 1 },
        { code: 'Digit0', label: '0', width: 1 },
        { code: 'Minus', label: '-', width: 1 },
        { code: 'Equal', label: '=', width: 1 },
        { code: 'Backspace', label: 'Delete', width: 2 }, null,
        { code: 'Insert', label: 'Insert', width: 1 },
        { code: 'Home', label: 'Home', width: 1 },
        { code: 'PageUp', label: 'Page Up', width: 1 }
      ],
      [
        { code: 'Tab', label: 'Tab', width: 1.5 },
        { code: 'KeyQ', label: 'Q', width: 1 },
        { code: 'KeyW', label: 'W', width: 1 },
        { code: 'KeyE', label: 'E', width: 1 },
        { code: 'KeyR', label: 'R', width: 1 },
        { code: 'KeyT', label: 'T', width: 1 },
        { code: 'KeyY', label: 'Y', width: 1 },
        { code: 'KeyU', label: 'U', width: 1 },
        { code: 'KeyI', label: 'I', width: 1 },
        { code: 'KeyO', label: 'O', width: 1 },
        { code: 'KeyP', label: 'P', width: 1 },
        { code: 'BracketLeft', label: '[', width: 1 },
        { code: 'BracketRight', label: ']', width: 1 },
        { code: 'Backslash', label: '\\', width: 1.5 }, null,
        { code: 'Delete', label: 'Delete', width: 1 },
        { code: 'End', label: 'End', width: 1 },
        { code: 'PageDown', label: 'Page Down', width: 1 }
      ],
      [
        { code: 'CapsLock', label: 'Caps Lock', width: 1.75 },
        { code: 'KeyA', label: 'A', width: 1 },
        { code: 'KeyS', label: 'S', width: 1 },
        { code: 'KeyD', label: 'D', width: 1 },
        { code: 'KeyF', label: 'F', width: 1 },
        { code: 'KeyG', label: 'G', width: 1 },
        { code: 'KeyH', label: 'H', width: 1 },
        { code: 'KeyJ', label: 'J', width: 1 },
        { code: 'KeyK', label: 'K', width: 1 },
        { code: 'KeyL', label: 'L', width: 1 },
        { code: 'Semicolon', label: ';', width: 1 },
        { code: 'Quote', label: "'", width: 1 },
        { code: 'Enter', label: 'Return', width: 2.25 }
      ],
      [
        { code: 'ShiftLeft', label: 'Shift', width: 2.25 },
        { code: 'KeyZ', label: 'Z', width: 1 },
        { code: 'KeyX', label: 'X', width: 1 },
        { code: 'KeyC', label: 'C', width: 1 },
        { code: 'KeyV', label: 'V', width: 1 },
        { code: 'KeyB', label: 'B', width: 1 },
        { code: 'KeyN', label: 'N', width: 1 },
        { code: 'KeyM', label: 'M', width: 1 },
        { code: 'Comma', label: ',', width: 1 },
        { code: 'Period', label: '.', width: 1 },
        { code: 'Slash', label: '/', width: 1 },
        { code: 'ShiftRight', label: 'Shift', width: 2.75 }, null, null,
        { code: 'ArrowUp', label: '↑', width: 1 }, null, null,
        { code: 'NumLock', label: 'Clear', width: 1 },
        { code: 'NumpadDivide', label: '/', width: 1 },
        { code: 'NumpadMultiply', label: '*', width: 1 },
        { code: 'NumpadSubtract', label: '-', width: 1 }
      ],
      [
        { code: 'ControlLeft', label: 'Control', width: 1.5 },
        { code: 'AltLeft', label: 'Option', width: 1.5 },
        { code: 'MetaLeft', label: 'Command', width: 1.5 },
        { code: 'Space', label: 'Space', width: 7 },
        { code: 'MetaRight', label: 'Command', width: 1.5 },
        { code: 'AltRight', label: 'Option', width: 1.5 },
        { code: 'ControlRight', label: 'Control', width: 1.5 }, null, null,
        { code: 'ArrowLeft', label: '←', width: 1 },
        { code: 'ArrowDown', label: '↓', width: 1 },
        { code: 'ArrowRight', label: '→', width: 1 }, null, null,
        { code: 'Numpad7', label: '7', width: 1 },
        { code: 'Numpad8', label: '8', width: 1 },
        { code: 'Numpad9', label: '9', width: 1 },
        { code: 'NumpadAdd', label: '+', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad4', label: '4', width: 1 },
        { code: 'Numpad5', label: '5', width: 1 },
        { code: 'Numpad6', label: '6', width: 1 }, null,
        { code: 'Numpad1', label: '1', width: 1 },
        { code: 'Numpad2', label: '2', width: 1 },
        { code: 'Numpad3', label: '3', width: 1 },
        { code: 'NumpadEnter', label: 'Enter', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad0', label: '0', width: 2 },
        { code: 'NumpadDecimal', label: '.', width: 1 }
      ]
    ]
  },
  
  gaming: {
    name: '游戏键盘',
    rows: [
      [
        { code: 'Escape', label: 'Esc', width: 1 }, null,
        { code: 'F1', label: 'F1', width: 1 },
        { code: 'F2', label: 'F2', width: 1 },
        { code: 'F3', label: 'F3', width: 1 },
        { code: 'F4', label: 'F4', width: 1 }, null,
        { code: 'F5', label: 'F5', width: 1 },
        { code: 'F6', label: 'F6', width: 1 },
        { code: 'F7', label: 'F7', width: 1 },
        { code: 'F8', label: 'F8', width: 1 }, null,
        { code: 'F9', label: 'F9', width: 1 },
        { code: 'F10', label: 'F10', width: 1 },
        { code: 'F11', label: 'F11', width: 1 },
        { code: 'F12', label: 'F12', width: 1 }, null,
        { code: 'PrintScreen', label: 'PrtSc', width: 1 },
        { code: 'ScrollLock', label: 'ScrLk', width: 1 },
        { code: 'Pause', label: 'Pause', width: 1 }
      ],
      [
        { code: 'Backquote', label: '`', width: 1 },
        { code: 'Digit1', label: '1', width: 1 },
        { code: 'Digit2', label: '2', width: 1 },
        { code: 'Digit3', label: '3', width: 1 },
        { code: 'Digit4', label: '4', width: 1 },
        { code: 'Digit5', label: '5', width: 1 },
        { code: 'Digit6', label: '6', width: 1 },
        { code: 'Digit7', label: '7', width: 1 },
        { code: 'Digit8', label: '8', width: 1 },
        { code: 'Digit9', label: '9', width: 1 },
        { code: 'Digit0', label: '0', width: 1 },
        { code: 'Minus', label: '-', width: 1 },
        { code: 'Equal', label: '=', width: 1 },
        { code: 'Backspace', label: 'Backspace', width: 2 }, null,
        { code: 'Insert', label: 'Insert', width: 1 },
        { code: 'Home', label: 'Home', width: 1 },
        { code: 'PageUp', label: 'Page Up', width: 1 }
      ],
      [
        { code: 'Tab', label: 'Tab', width: 1.5 },
        { code: 'KeyQ', label: 'Q', width: 1 },
        { code: 'KeyW', label: 'W', width: 1 },
        { code: 'KeyE', label: 'E', width: 1 },
        { code: 'KeyR', label: 'R', width: 1 },
        { code: 'KeyT', label: 'T', width: 1 },
        { code: 'KeyY', label: 'Y', width: 1 },
        { code: 'KeyU', label: 'U', width: 1 },
        { code: 'KeyI', label: 'I', width: 1 },
        { code: 'KeyO', label: 'O', width: 1 },
        { code: 'KeyP', label: 'P', width: 1 },
        { code: 'BracketLeft', label: '[', width: 1 },
        { code: 'BracketRight', label: ']', width: 1 },
        { code: 'Backslash', label: '\\', width: 1.5 }, null,
        { code: 'Delete', label: 'Delete', width: 1 },
        { code: 'End', label: 'End', width: 1 },
        { code: 'PageDown', label: 'Page Down', width: 1 }
      ],
      [
        { code: 'CapsLock', label: 'Caps Lock', width: 1.75 },
        { code: 'KeyA', label: 'A', width: 1 },
        { code: 'KeyS', label: 'S', width: 1 },
        { code: 'KeyD', label: 'D', width: 1 },
        { code: 'KeyF', label: 'F', width: 1 },
        { code: 'KeyG', label: 'G', width: 1 },
        { code: 'KeyH', label: 'H', width: 1 },
        { code: 'KeyJ', label: 'J', width: 1 },
        { code: 'KeyK', label: 'K', width: 1 },
        { code: 'KeyL', label: 'L', width: 1 },
        { code: 'Semicolon', label: ';', width: 1 },
        { code: 'Quote', label: "'", width: 1 },
        { code: 'Enter', label: 'Enter', width: 2.25 }
      ],
      [
        { code: 'ShiftLeft', label: 'Shift', width: 2.25 },
        { code: 'KeyZ', label: 'Z', width: 1 },
        { code: 'KeyX', label: 'X', width: 1 },
        { code: 'KeyC', label: 'C', width: 1 },
        { code: 'KeyV', label: 'V', width: 1 },
        { code: 'KeyB', label: 'B', width: 1 },
        { code: 'KeyN', label: 'N', width: 1 },
        { code: 'KeyM', label: 'M', width: 1 },
        { code: 'Comma', label: ',', width: 1 },
        { code: 'Period', label: '.', width: 1 },
        { code: 'Slash', label: '/', width: 1 },
        { code: 'ShiftRight', label: 'Shift', width: 2.75 }, null,
        { code: 'ArrowUp', label: '↑', width: 1 }, null,
        { code: 'NumLock', label: 'Num Lock', width: 1 },
        { code: 'NumpadDivide', label: '/', width: 1 },
        { code: 'NumpadMultiply', label: '*', width: 1 },
        { code: 'NumpadSubtract', label: '-', width: 1 }
      ],
      [
        { code: 'ControlLeft', label: 'Ctrl', width: 1.25 },
        { code: 'MetaLeft', label: 'Win', width: 1.25 },
        { code: 'AltLeft', label: 'Alt', width: 1.25 },
        { code: 'Space', label: 'Space', width: 5 },
        { code: 'AltRight', label: 'Alt', width: 1.25 },
        { code: 'MetaRight', label: 'Win', width: 1.25 },
        { code: 'ContextMenu', label: 'Menu', width: 1.25 },
        { code: 'ControlRight', label: 'Ctrl', width: 1.25 }, null,
        { code: 'ArrowLeft', label: '←', width: 1 },
        { code: 'ArrowDown', label: '↓', width: 1 },
        { code: 'ArrowRight', label: '→', width: 1 }, null,
        { code: 'Numpad7', label: '7', width: 1 },
        { code: 'Numpad8', label: '8', width: 1 },
        { code: 'Numpad9', label: '9', width: 1 },
        { code: 'NumpadAdd', label: '+', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad4', label: '4', width: 1 },
        { code: 'Numpad5', label: '5', width: 1 },
        { code: 'Numpad6', label: '6', width: 1 }, null,
        { code: 'Numpad1', label: '1', width: 1 },
        { code: 'Numpad2', label: '2', width: 1 },
        { code: 'Numpad3', label: '3', width: 1 },
        { code: 'NumpadEnter', label: 'Enter', width: 1, height: 2 }
      ],
      [
        { code: 'Numpad0', label: '0', width: 2 },
        { code: 'NumpadDecimal', label: '.', width: 1 }
      ]
    ]
  },
  
  laptop: {
    name: '笔记本键盘',
    rows: [
      [
        { code: 'Escape', label: 'Esc', width: 1 }, null,
        { code: 'F1', label: 'F1', width: 1 },
        { code: 'F2', label: 'F2', width: 1 },
        { code: 'F3', label: 'F3', width: 1 },
        { code: 'F4', label: 'F4', width: 1 }, null,
        { code: 'F5', label: 'F5', width: 1 },
        { code: 'F6', label: 'F6', width: 1 },
        { code: 'F7', label: 'F7', width: 1 },
        { code: 'F8', label: 'F8', width: 1 }, null,
        { code: 'F9', label: 'F9', width: 1 },
        { code: 'F10', label: 'F10', width: 1 },
        { code: 'F11', label: 'F11', width: 1 },
        { code: 'F12', label: 'F12', width: 1 }, null,
        { code: 'Insert', label: 'Insert', width: 1 },
        { code: 'Delete', label: 'Delete', width: 1 }
      ],
      [
        { code: 'Backquote', label: '`', width: 1 },
        { code: 'Digit1', label: '1', width: 1 },
        { code: 'Digit2', label: '2', width: 1 },
        { code: 'Digit3', label: '3', width: 1 },
        { code: 'Digit4', label: '4', width: 1 },
        { code: 'Digit5', label: '5', width: 1 },
        { code: 'Digit6', label: '6', width: 1 },
        { code: 'Digit7', label: '7', width: 1 },
        { code: 'Digit8', label: '8', width: 1 },
        { code: 'Digit9', label: '9', width: 1 },
        { code: 'Digit0', label: '0', width: 1 },
        { code: 'Minus', label: '-', width: 1 },
        { code: 'Equal', label: '=', width: 1 },
        { code: 'Backspace', label: 'Backspace', width: 2 }
      ],
      [
        { code: 'Tab', label: 'Tab', width: 1.5 },
        { code: 'KeyQ', label: 'Q', width: 1 },
        { code: 'KeyW', label: 'W', width: 1 },
        { code: 'KeyE', label: 'E', width: 1 },
        { code: 'KeyR', label: 'R', width: 1 },
        { code: 'KeyT', label: 'T', width: 1 },
        { code: 'KeyY', label: 'Y', width: 1 },
        { code: 'KeyU', label: 'U', width: 1 },
        { code: 'KeyI', label: 'I', width: 1 },
        { code: 'KeyO', label: 'O', width: 1 },
        { code: 'KeyP', label: 'P', width: 1 },
        { code: 'BracketLeft', label: '[', width: 1 },
        { code: 'BracketRight', label: ']', width: 1 },
        { code: 'Backslash', label: '\\', width: 1.5 }
      ],
      [
        { code: 'CapsLock', label: 'Caps Lock', width: 1.75 },
        { code: 'KeyA', label: 'A', width: 1 },
        { code: 'KeyS', label: 'S', width: 1 },
        { code: 'KeyD', label: 'D', width: 1 },
        { code: 'KeyF', label: 'F', width: 1 },
        { code: 'KeyG', label: 'G', width: 1 },
        { code: 'KeyH', label: 'H', width: 1 },
        { code: 'KeyJ', label: 'J', width: 1 },
        { code: 'KeyK', label: 'K', width: 1 },
        { code: 'KeyL', label: 'L', width: 1 },
        { code: 'Semicolon', label: ';', width: 1 },
        { code: 'Quote', label: "'", width: 1 },
        { code: 'Enter', label: 'Enter', width: 2.25 }
      ],
      [
        { code: 'ShiftLeft', label: 'Shift', width: 2.25 },
        { code: 'KeyZ', label: 'Z', width: 1 },
        { code: 'KeyX', label: 'X', width: 1 },
        { code: 'KeyC', label: 'C', width: 1 },
        { code: 'KeyV', label: 'V', width: 1 },
        { code: 'KeyB', label: 'B', width: 1 },
        { code: 'KeyN', label: 'N', width: 1 },
        { code: 'KeyM', label: 'M', width: 1 },
        { code: 'Comma', label: ',', width: 1 },
        { code: 'Period', label: '.', width: 1 },
        { code: 'Slash', label: '/', width: 1 },
        { code: 'ShiftRight', label: 'Shift', width: 2.75 }
      ],
      [
        { code: 'ControlLeft', label: 'Ctrl', width: 1.25 },
        { code: 'MetaLeft', label: 'Win', width: 1.25 },
        { code: 'AltLeft', label: 'Alt', width: 1.25 },
        { code: 'Space', label: 'Space', width: 6.25 },
        { code: 'AltRight', label: 'Alt', width: 1.25 },
        { code: 'MetaRight', label: 'Win', width: 1.25 },
        { code: 'ContextMenu', label: 'Menu', width: 1.25 },
        { code: 'ControlRight', label: 'Ctrl', width: 1.25 }
      ]
    ]
  }
};